# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: mycluster.icp:8500/default/cardashboard
hpa:
  enabled: false
cloud_services:
  conversation:
    credentials: '{
  "url": "https://gateway.watsonplatform.net/assistant/api",
  "username": "58d87df0-fd3b-48be-83d5-1ca31f395e76",
  "password": "DHoeSI6PruAh"
}'
